name: 'Conventional commit pull request checker'
description: 'Checks pull request title and body to adhere to conventional commits standard'
author: 'oleksiireshetnik'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'git-commit'
  color: 'green'

# Define your inputs here.
inputs:
  title-check-enabled:
    description: ''
    required: false
    default: 'true'

  title-max-len:
    description: ''
    required: false
    default: '-1'

  description-check-enabled:
    description: ''
    required: false
    default: 'false'

  description-required:
    description: ''
    required: false
    default: 'false'

  description-max-len:
    description: ''
    required: false
    default: '-1'

  ignored-contributors:
    description: 'Determines users that are exempt from this action'
    required: false
    default: ''

runs:
  using: node20
  main: dist/index.js
